### ISSUE TITLE
What about default values

### ISSUE THREAD

**Issue by mehrdaad** [AltThree/TestBench#14]
Validation checks check weather a validation rule starts with required or nullable.  
But there are circumstances that a field is not required and if anything is not provided a default value is added.  
How to handle those checks?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Sorry we totally missed this issue!

> But there are circumstances that a field is not required and if anything is not provided a default value is added.

So, the context here is that we were using this code on an internal project, and thought we might as well open source it. It wasn't built with public use in mind, as such, so some of the code is very much geared to just do what we needed.

> How to handle those checks?

We'd definitely look at any incoming PRs that made things more flexible for people to use. :)

**Comment by GrahamCampbell** [comment]
Ping @mehrdaad. :)
